version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    # Try to remove the PR limit
    open-pull-requests-limit: 999
    versioning-strategy: increase
